
name: Run

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [0 10,10 20,20 30,30 40,40 50,50 60,60 70,70 80,80 90,90 100,100 110,110 120,120 130,130 140,140 150,150 160,160 170,170 180,180 190,190 200]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install selenium
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python run-t.py ${{matrix.RangeIndex}}
      - name: done
        run: exit
